name: EKS-Pipeline
on:
  workflow_dispatch:

jobs:
  CLUSTER-SETUP:
    runs-on: [self-hosted, EKS]
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      # AWS_ACCESS_KEY_ID: "{{ secrets.AWS_ACCESS_KEY_ID }}"
      # AWS_SECRET_ACCESS_KEY: "{{ secrets.AWS_SECRET_ACCESS_KEY_}}"
      nodes: 3
      node_type: "t2.micro"
    container:
      image: litmuschaos/cypress:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Settings up EKS Cluster
        run: |
          chmod 755 k8s/eks/1-cluster-setup/setup
          k8s/eks/1-cluster-setup/setup

  CLUSTER-CLEANUP:
    runs-on: [self-hosted, EKS]
    needs: CLUSTER-SETUP
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      # AWS_ACCESS_KEY_ID: "{{ secrets.AWS_ACCESS_KEY_ID }}"
      # AWS_SECRET_ACCESS_KEY: "{{ secrets.AWS_SECRET_ACCESS_KEY_}}"
      nodes: 3
      node_type: "t2.micro"
    container:
      image: litmuschaos/cypress:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tearing down EKS Cluster
        run: |
          chmod 755 k8s/eks/2-cluster-cleanup/cleanup
          k8s/eks/2-cluster-cleanup/cleanup
