name: EKS-Pipeline
on:
  workflow_dispatch:

jobs:
  CLUSTER-1-SETUP:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      nodes: 3
      node_type: "t2.medium"
      CLUSTER_NUM: 1
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Settings up EKS Cluster
        run: |
          chmod 755 k8s/eks/1-cluster-setup/setup
          k8s/eks/1-cluster-setup/setup
      - name: Uploading kube-config as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: kube-config
          path: ".kube/"

  # CLUSTER-2-SETUP:
  #   runs-on: ubuntu-latest
  #   env:
  #     CI_PIPELINE_ID: ${{ github.run_id }}
  #     region: "eu-west-2"
  #     AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  #     AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  #     nodes: 2
  #     node_type: "t2.micro"
  #     CLUSTER_NUM: 2
  #   container:
  #     image: jonsy13/kubera-litmus:latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Settings up EKS Cluster
  #       run: |
  #         chmod 755 k8s/eks/1-cluster-setup/setup
  #         k8s/eks/1-cluster-setup/setup

  PORTAL-SETUP:
    needs: CLUSTER-1-SETUP
    runs-on: ubuntu-latest
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Downloading artifacts
        uses: actions/download-artifact@v2
        with:
          name: kube-config
      - name: Setting Up Litmus-Portal on Cluster-1
        run: |
          ls -R
          chmod 755 ./litmus/setup.sh
          ./litmus/setup.sh

  PORTAL-CLEANUP:
    needs: PORTAL-SETUP
    runs-on: ubuntu-latest
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Downloading artifacts
        uses: actions/download-artifact@v2
        with:
          name: kube-config
      - name: Litmus-Portal Cleanup
        run: |
          chmod 755 ./litmus/cleanup.sh
          ./litmus/cleanup.sh

  CLUSTER-1-CLEANUP:
    if: always()
    runs-on: ubuntu-latest
    needs: PORTAL-CLEANUP
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      CLUSTER_NUM: 1
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tearing down EKS Cluster
        run: |
          chmod 755 k8s/eks/2-cluster-cleanup/cleanup
          k8s/eks/2-cluster-cleanup/cleanup

  # CLUSTER-2-CLEANUP:
  #   if: always()
  #   runs-on: ubuntu-latest
  #   needs: CLUSTER-2-SETUP
  #   env:
  #     CI_PIPELINE_ID: ${{ github.run_id }}
  #     region: "eu-west-2"
  #     AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  #     AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  #     CLUSTER_NUM: 2
  #   container:
  #     image: jonsy13/kubera-litmus:latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Tearing down EKS Cluster
  #       run: |
  #         chmod 755 k8s/eks/2-cluster-cleanup/cleanup
  #         k8s/eks/2-cluster-cleanup/cleanup
