name: EKS-Pipeline
on:
  workflow_dispatch:

jobs:
  CLUSTER-1-SETUP:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      nodes: 3
      node_type: "t2.medium"
      CLUSTER_NUM: 1
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Settings up EKS Cluster
        run: |
          chmod 755 k8s/eks/1-cluster-setup/setup
          k8s/eks/1-cluster-setup/setup

  CLUSTER-2-SETUP:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      nodes: 2
      node_type: "t2.micro"
      CLUSTER_NUM: 2
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Settings up EKS Cluster
        run: |
          chmod 755 k8s/eks/1-cluster-setup/setup
          k8s/eks/1-cluster-setup/setup

  CLUSTER-1-CLEANUP:
    if: always()
    runs-on: ubuntu-latest
    needs: CLUSTER-1-SETUP
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      CLUSTER_NUM: 1
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tearing down EKS Cluster
        run: |
          chmod 755 k8s/eks/2-cluster-cleanup/cleanup
          k8s/eks/2-cluster-cleanup/cleanup

  CLUSTER-2-CLEANUP:
    if: always()
    runs-on: ubuntu-latest
    needs: CLUSTER-2-SETUP
    env:
      CI_PIPELINE_ID: ${{ github.run_id }}
      region: "eu-west-2"
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      CLUSTER_NUM: 2
    container:
      image: jonsy13/kubera-litmus:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tearing down EKS Cluster
        run: |
          chmod 755 k8s/eks/2-cluster-cleanup/cleanup
          k8s/eks/2-cluster-cleanup/cleanup
