name: EKS-Pipeline
on:
  workflow_dispatch:

jobs:
  Chaos-Eks-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        run: |
          aws configure set default.region ${region}
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
          aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        env:
          region: "eu-west-2"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - run: aws version

      - run: aws eks --region eu-west-2 update-kubeconfig --name vedant-test-cluster

      - name: Checking connection
        run: |
          kubectl get nodes
          kubectl get pods -A

      # - name: Setting up kubeconfig ENV for Github Chaos Action
      #   run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      # - name: Setup Litmus
      #   uses: litmuschaos/github-chaos-actions@v0.4.0
      #   env:
      #     INSTALL_LITMUS: true

      # - name: Running Litmus pod delete chaos experiment
      #   uses: litmuschaos/github-chaos-actions@v0.4.0
      #   env:
      #     EXPERIMENT_NAME: pod-delete
      #     EXPERIMENT_IMAGE: litmuschaos/go-runner
      #     EXPERIMENT_IMAGE_TAG: latest
      #     JOB_CLEANUP_POLICY: delete

      # - name: Uninstall Litmus
      #   uses: litmuschaos/github-chaos-actions@v0.4.0
      #   env:
      #     LITMUS_CLEANUP: true
