name: EKS-Pipeline
on:
  workflow_dispatch:

jobs:
  Chaos-Eks-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - run: |
          export PATH=$PATH:/usr/local/bin/aws

      - run: |
          whereis aws
          echo $PATH

      - run: aws --version

      - run: |
          aws eks --region eu-west-2 update-kubeconfig --name vedant-test-cluster
          cat $HOME/.kube/config

      - name: Checking Cluster connection
        run: |
          kubectl get nodes
          kubectl get pods -A
          kubectl create deployment nginx --image nginx

      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        uses: litmuschaos/github-chaos-actions@v0.4.0
        env:
          INSTALL_LITMUS: true

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.4.0
        env:
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: latest
          JOB_CLEANUP_POLICY: delete

      - name: Uninstall Litmus
        uses: litmuschaos/github-chaos-actions@v0.4.0
        env:
          LITMUS_CLEANUP: true
