name: CI

on:
  workflow_dispatch:

jobs:
  Tests-Finder: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "portal"
          fetch-depth: 0
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: cd Cypress/cypress/integration/Parallel_Tests/ && echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq
  Parallel-Tests:
    runs-on: ubuntu-latest
    needs: [directories] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "portal"
          fetch-depth: 0
      - name: Running Parallel tests
        uses: cypress-io/github-action@v2
        continue-on-error: false
        with:
          spec: cypress/integration/Parallel_Tests/${{matrix.dir}}/*.spec.js
          working-directory: Cypress/
          config-file: cypress.prod.json
